declare const DOSWASMSETTINGS: {
    CLOUDSAVEURL: string;
    DEFAULTIMG: string;
};

declare const ROMLIST: Array<{
    url?: string;
    title?: string;
    skipiso?: string;
    ram?: string;
}>;

declare class MyClass {
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    rgbaDestination: Uint8ClampedArray;
    showFPS: boolean;
    onscreenKeyboard: boolean;
    lastHeapLength: number;
    rom_name: string;
    rom_size: number;
    iosMode: boolean;
    base_name: string;
    initCount: number;
    baseImageSaved: boolean;
    isoSaved: boolean;
    exportFilesRequested: boolean;
    canvasHeight: number;
    ram: number;
    initialHardDrive: string;
    dosVersion: string;
    iso_loaded: boolean;
    noIso: boolean;
    importedFileNames: string[];
    isSpecialHandler: boolean;
    img_loaded: boolean;
    cueFile: string;
    hasBinCue: boolean;
    audioInited: boolean;
    dblistSavestates: any[];
    dblistBaseImages: any[];
    dblistIsos: any[];
    multiFiles: any[];
    multiFileMode: boolean;
    singleFileUpload: boolean;
    loading: boolean;
    isoName: string;
    loginModalOpened: boolean;
    noCloudSave: boolean;
    dosSaveStates: any[];
    allSaveStates: any[];
    baseHardDrive: Uint8Array;
    compareCount: number;
    doIntegrityCheck: boolean;
    showLoadAndSavestate: boolean;
    loadSavestateAfterBoot: boolean;
    autoKeyboard: boolean;
    autoKeyboardTimer: number;
    autoKeyboardInterval: number;
    lastCalledTime: Date;
    fpscounter: number;
    currentfps: number;
    fpsInterval: number;
    then: number;
    hardDiskFallbackFromFloppy: boolean;
    ranWindowsSetup: boolean;
    win95InstallationFix: boolean;
    winNotFoundCommands: string;
    doswasmxBatFound: boolean;
    specialFileHandlers: string[];
    rivetsData: any;
    // rivetsData: {
    //     mobileMode: boolean;
    //     darkMode: boolean;
    //     inputController: InputController | null;
    //     cpu: string;
    //     beforeEmulatorStarted: boolean;
    //     loggedIn: boolean;
    //     romList: any[];
    //     hasCloud: boolean;
    //     password: string;
    //     message: string;
    //     moduleInitializing: boolean;
    //     dblistDisks: any[];
    //     settings: {
    //         CLOUDSAVEURL: string;
    //         DEFAULTIMG: string;
    //     };
    //     isoMounted: boolean;
    //     noLocalSave: boolean;
    //     floppyMounted: boolean;
    //     isDosMode: boolean;
    //     lblError: string;
    //     initialInstallation: boolean;
    //     changeCD: boolean;
    //     changeFloppy: boolean;
    //     loadFloppy: boolean;
    //     noCopyImport: boolean;
    //     ramTemp?: number;
    //     initialHardDriveTemp?: string;
    //     dosVersionTemp?: string;
    //     importStatus?: string;
    //     showProgress?: boolean;
    // };
    configuration: {
        startupScript: string;
    };

    constructor();
    btnDarkMode(): void;
    detectBrowser(): void;
    setupDragDropRom(): void;
    preventDefaults(e: Event): void;
    dragDropHighlight(e: Event): void;
    dragDropUnHighlight(e: Event): void;
    handleDrop(e: DragEvent): void;
    handleProgress(event: ProgressEvent<FileReader>, file: File): void;
    configureEmulator(): void;
    onAnimationFrame(): void;
    processPrintStatement(text: string): void;
    initModule(): Promise<void>;
    finishInitialization(): void;
    uploadBrowse(): void;
    importBrowse(): void;
    detectSingleFileUpload(fileName: string): void;
    checkIfImgMakeNeeded(files: FileList): void;
    uploadRom(event: Event): void;
    parseMultipleFiles(): Promise<void>;
    handleMultipleFiles(files: FileList, index: number): void;
    LoadEmulator(byteArray: Uint8Array): Promise<void>;
    hideMobileMenu(): void;
    setupMobileMode(): void;
    sanitizeName(name: string): string;
    readRomProp(key: string): void;
    loadRomAndSavestate(): void;
    extractRomName(name: string): string;
    loadRom(noIso?: boolean): Promise<void>;
    initAudio(): Promise<void>;
    AudioProcessRecurring(audioProcessingEvent: AudioProcessingEvent): void;
    countFPS(): void;
    extractBaseName(): void;
    load_file(path: string): Promise<void>;
    load_url_request(path: string): void;
    newRom(): void;
    onError(message: string): void;
    dropdownKeyDown(e: KeyboardEvent): void;
    fullscreen(): void;
    zoomIn(): void;
    zoomOut(): void;
    mouseDecreaseSpeed(): void;
    mouseIncreaseSpeed(): void;
    speedUp(): void;
    slowDown(): void;
    resizeCanvas(): void;
    saveDrive(): void;
    readFromLocalStorage(localStorageName: string, name: string): void;
    writeToLocalStorage(localStorageName: string, name: string): void;
    retrieveSettings(): void;
    saveOptions(): void;
    createDB(): void;
    findSavestateInDatabase(): void;
    saveToDatabase(data: Uint8Array, saveType: string): void;
    loadFromDatabase(saveType: string): void;
    clearHardDrive(): void;
    WriteConfigFile(): void;
    clearDatabase(): void;
    unzipFile(arrayBuffer: ArrayBuffer): Promise<void>;
    toggleOnscreenKeyboard(): void;
    toggleFPS(): void;
    exportModal(): void;
    settingsModal(): void;
    settingsSubmit(): void;
    importModal(importType?: string): void;
    exportFiles(): void;
    saveStateLocal(): void;
    loadStateLocal(): void;
    SaveStateEvent(): void;
    loadHardDriveDiffs(byteArray: Uint8Array): Promise<Uint8Array>;
    applyHardDriveDiffs(byteArrayDiffs: Uint8Array, resolve: (value: Uint8Array) => void): Promise<void>;
    saveHardDriveDiffs(): Promise<void>;
    compressArrayBuffer(input: ArrayBuffer): Promise<Uint8Array>;
    decompressArrayBuffer(input: ArrayBuffer): Promise<Uint8Array>;
    exportHardDrive(): void;
    importFiles(event: Event): void;
    processImportFiles(files: FileList, index: number): void;
    exitToDos(): void;
    cacheIsoAndBaseImage(): void;
    saveCloud(): void;
    loadCloud(): void;
    setupLogin(): Promise<void>;
    loginModal(): void;
    logout(): void;
    loginSubmit(): Promise<void>;
    loginSilent(): Promise<void>;
    postLoginProcess(): void;
    convertCSharpDateTime(initialDate: string): Date;
    loginToServer(): Promise<string>;
    getSaveStates(): Promise<void>;
    integrityCheck(newHardDriveBytes: Uint8Array): Promise<void>;
    togglePause(): void;
    updateCPU(value: string): void;
    sendCtrlAltDel(): void;
    toggle16BitColorFix(): void;
    toggleAlwaysUseBackbuffer(): void;
    toggleAutoKeybaord(): void;
    tickAutoKeyboard(): void;
    turboSpeed(): void;
    HandleMessage(name: string, props: any): void;
    Run(): void;
    sleepHandler(e: MessageEvent): void;
    UploadFiles(): Promise<void>;
    printError(text: string): void;
    updateCanvas(rgbSource: Uint8Array): void;
    canvasClick(): void;
    captureMouse(): void;
    setupInputController(): void;
}

declare class InputController {
    constructor();
    Key_Up: boolean;
    Key_Down: boolean;
    Key_Left: boolean;
    Key_Right: boolean;
    Key_Action_A: boolean;
    Key_Action_B: boolean;
    Key_Action_Start: boolean;
    Key_Action_L: boolean;
    Key_Action_R: boolean;
    VectorX: number;
    VectorY: number;
    setupMouseMode(): void;
    setupMobileControls(touch_element_id: string): void;
    processGamepad(): void;
    updateControls(): void;
    updateDosControls(): void;
}

declare const myApp: MyClass;
// declare const Module: any;
