name: Check Version Update on Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  check-version-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Check
        id: version-check
        uses: EndBug/version-check@v3.0.0
        with:
          file-url: https://raw.githubusercontent.com/${{ github.event.pull_request.base.repo.full_name }}/${{ github.event.pull_request.base.ref }}/package.json
          static-checking: localIsNew
      - name: Fail when unchanged
        if: steps.version-check.outputs.changed == 'false'
        run: 'echo "No version change detected. Please update the version in package.json." && exit 1'
  